### ISSUE TITLE
Window Size

### ISSUE THREAD

**Issue by eqnguyen** [Inforcer25/The-Forest-Server-Manager#1]
The window is not resizable, so the text gets cut off on screens with different resolutions. I can't edit certain fields like the IP address.

**Comment by Inforcer25** [comment]
I get on it right now. Thanks for reporting this.

**Comment by Inforcer25** [comment]
Issue has been fixed. https://github.com/Inforcer25/The-Forest-Server-Manager/releases/tag/1.5
