### ISSUE TITLE
style not found 

### ISSUE THREAD

**Issue by beals1pt0** [Inforcer25/The-Forest-Server-Manager#2]
it seems every time i start the program it tells me style not found still loads but is ver annoying 

also, can select any other style nore type what setting you have in your pics

**Comment by Inforcer25** [comment]
This is a bug i still have to fix.
This can be fixed my just changing the style to to anything else. If there is no styles to choose from delete the setting.ini file. It can be located here: `C:\Users\USER\AppData\Roaming\TheForestServerManager`

This will be fixed next update

**Comment by Inforcer25** [comment]
Fix release https://github.com/Inforcer25/The-Forest-Server-Manager/releases/tag/v1.5.2
