### ISSUE TITLE
Boats stop rowing on using this launcher...

### ISSUE THREAD

**Issue by Jamesfle** [Inforcer25/The-Forest-Server-Manager#5]
Ive used the vanilla launcher for a while now and boats were always fine. Today, i installed the server again via your launcher because i keep reading about "Boats not working". So i tried your launcher and same happened to me now, i can push boats but not row them.

I've been digging and asking questions. Finally got 2 things in common. Your launcher and Oxide. Ive asked Oxide already, who have stated that it cant be them. So kinda leaves your program as the culprit. Can you look into it, see if i am correct?

**Comment by Inforcer25** [comment]
As you said it happened before and after using TFSM. TFSM has no connection to your server and has no power in modding it or changing it in any way. All it does it download your server using steamcmd and gives you the option to install oxidemod although its needed to fix some server issues. People are also having this issue on just co-op so yeah, It's not the fault of TFSM.

More info: http://steamcommunity.com/app/242760/discussions/1/333656722971485932/
